import { StaffSalary, SalaryPayment, SalaryComponent, SalaryStats } from "@/lib/admin/types/salary";

// Salary Components (Allowances & Deductions)
export const salaryComponents: SalaryComponent[] = [
    { id: "comp-1", name: "House Rent Allowance", type: "allowance", value: 15, isPercentage: true },
    { id: "comp-2", name: "Transport Allowance", type: "allowance", value: 5000, isPercentage: false },
    { id: "comp-3", name: "Medical Allowance", type: "allowance", value: 3000, isPercentage: false },
    { id: "comp-4", name: "Provident Fund", type: "deduction", value: 8, isPercentage: true },
    { id: "comp-5", name: "Professional Tax", type: "deduction", value: 200, isPercentage: false },
    { id: "comp-6", name: "Income Tax", type: "deduction", value: 5, isPercentage: true },
];

// Staff Salary Data
export const staffSalaries: StaffSalary[] = [
    {
        id: "sal-1",
        staffId: "ins-1",
        staffName: "Sarah Johnson",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
        department: "Science",
        designation: "Senior Teacher",
        staffType: "teaching",
        joiningDate: "2020-06-15",
        email: "sarah.j@school.edu",
        phone: "0300-1234567",
        bankAccount: "HBL-1234567890",
        baseSalary: 85000,
        allowances: [
            { name: "House Rent", amount: 12750 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 6800 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 4250 },
        ],
        grossSalary: 105750,
        netSalary: 94500,
    },
    {
        id: "sal-2",
        staffId: "ins-2",
        staffName: "Michael Chen",
        avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=150",
        department: "Mathematics",
        designation: "Head of Department",
        staffType: "teaching",
        joiningDate: "2018-09-01",
        email: "m.chen@school.edu",
        phone: "0301-2345678",
        bankAccount: "UBL-0987654321",
        baseSalary: 120000,
        allowances: [
            { name: "House Rent", amount: 18000 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
            { name: "HOD Allowance", amount: 10000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 9600 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 7800 },
        ],
        grossSalary: 156000,
        netSalary: 138400,
    },
    {
        id: "sal-3",
        staffId: "ins-3",
        staffName: "Emily Davis",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=150",
        department: "English",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2022-01-10",
        email: "emily.d@school.edu",
        phone: "0302-3456789",
        baseSalary: 65000,
        allowances: [
            { name: "House Rent", amount: 9750 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 5200 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 82750,
        netSalary: 77350,
    },
    {
        id: "sal-4",
        staffId: "staff-1",
        staffName: "Ahmed Khan",
        department: "Administration",
        designation: "Office Manager",
        staffType: "admin",
        joiningDate: "2019-03-20",
        email: "a.khan@school.edu",
        phone: "0303-4567890",
        bankAccount: "MCB-1122334455",
        baseSalary: 55000,
        allowances: [
            { name: "House Rent", amount: 8250 },
            { name: "Transport", amount: 5000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4400 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 68250,
        netSalary: 63650,
    },
    {
        id: "sal-5",
        staffId: "staff-2",
        staffName: "Fatima Bibi",
        department: "Maintenance",
        designation: "Cleaning Staff",
        staffType: "non-teaching",
        joiningDate: "2021-07-05",
        email: "f.bibi@school.edu",
        phone: "0304-5678901",
        baseSalary: 32000,
        allowances: [
            { name: "Transport", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 2560 },
        ],
        grossSalary: 35000,
        netSalary: 32440,
    },
    {
        id: "sal-6",
        staffId: "ins-4",
        staffName: "Robert Wilson",
        department: "History",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2020-08-15",
        email: "r.wilson@school.edu",
        phone: "0305-6789012",
        baseSalary: 70000,
        allowances: [
            { name: "House Rent", amount: 10500 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 5600 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 3500 },
        ],
        grossSalary: 88500,
        netSalary: 79200,
    },
    {
        id: "sal-7",
        staffId: "ins-5",
        staffName: "Jessica Taylor",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150",
        department: "Science",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2021-02-28",
        email: "j.taylor@school.edu",
        phone: "0306-7890123",
        baseSalary: 68000,
        allowances: [
            { name: "House Rent", amount: 10200 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 5440 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 3400 },
        ],
        grossSalary: 86200,
        netSalary: 77160,
    },
    {
        id: "sal-8",
        staffId: "staff-3",
        staffName: "Muhammad Ali",
        department: "Security",
        designation: "Security Guard",
        staffType: "non-teaching",
        joiningDate: "2020-11-10",
        email: "m.ali@school.edu",
        phone: "0307-8901234",
        baseSalary: 35000,
        allowances: [
            { name: "Transport", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 2800 },
        ],
        grossSalary: 38000,
        netSalary: 35200,
    },
    {
        id: "sal-9",
        staffId: "ins-6",
        staffName: "David Miller",
        department: "Mathematics",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2022-08-01",
        email: "d.miller@school.edu",
        phone: "0308-9012345",
        baseSalary: 62000,
        allowances: [
            { name: "House Rent", amount: 9300 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4960 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 79300,
        netSalary: 74140,
    },
    {
        id: "sal-10",
        staffId: "staff-4",
        staffName: "Zainab Hassan",
        department: "Library",
        designation: "Librarian",
        staffType: "non-teaching",
        joiningDate: "2019-05-15",
        email: "z.hassan@school.edu",
        phone: "0309-0123456",
        bankAccount: "ABL-5566778899",
        baseSalary: 48000,
        allowances: [
            { name: "House Rent", amount: 7200 },
            { name: "Transport", amount: 5000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 3840 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 60200,
        netSalary: 56160,
    },
    {
        id: "sal-11",
        staffId: "ins-7",
        staffName: "Ayesha Malik",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
        department: "Urdu",
        designation: "Senior Teacher",
        staffType: "teaching",
        joiningDate: "2019-04-10",
        email: "a.malik@school.edu",
        phone: "0310-1234567",
        bankAccount: "HBL-9988776655",
        baseSalary: 78000,
        allowances: [
            { name: "House Rent", amount: 11700 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 6240 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 3900 },
        ],
        grossSalary: 97700,
        netSalary: 87360,
    },
    {
        id: "sal-12",
        staffId: "ins-8",
        staffName: "James Anderson",
        department: "Physical Education",
        designation: "Sports Coach",
        staffType: "teaching",
        joiningDate: "2021-03-15",
        email: "j.anderson@school.edu",
        phone: "0311-2345678",
        baseSalary: 55000,
        allowances: [
            { name: "House Rent", amount: 8250 },
            { name: "Transport", amount: 5000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4400 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 68250,
        netSalary: 63650,
    },
    {
        id: "sal-13",
        staffId: "staff-5",
        staffName: "Rashid Hussain",
        department: "IT",
        designation: "System Administrator",
        staffType: "non-teaching",
        joiningDate: "2020-06-01",
        email: "r.hussain@school.edu",
        phone: "0312-3456789",
        bankAccount: "MCB-4455667788",
        baseSalary: 72000,
        allowances: [
            { name: "House Rent", amount: 10800 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 5760 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 3600 },
        ],
        grossSalary: 90800,
        netSalary: 81240,
    },
    {
        id: "sal-14",
        staffId: "ins-9",
        staffName: "Sophia Martinez",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150",
        department: "Art",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2022-09-01",
        email: "s.martinez@school.edu",
        phone: "0313-4567890",
        baseSalary: 58000,
        allowances: [
            { name: "House Rent", amount: 8700 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4640 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 74700,
        netSalary: 69860,
    },
    {
        id: "sal-15",
        staffId: "staff-6",
        staffName: "Imran Shah",
        department: "Accounts",
        designation: "Accountant",
        staffType: "admin",
        joiningDate: "2018-01-15",
        email: "i.shah@school.edu",
        phone: "0314-5678901",
        bankAccount: "UBL-3344556677",
        baseSalary: 68000,
        allowances: [
            { name: "House Rent", amount: 10200 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 5440 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 3400 },
        ],
        grossSalary: 86200,
        netSalary: 77160,
    },
    {
        id: "sal-16",
        staffId: "ins-10",
        staffName: "Olivia Brown",
        department: "Music",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2023-01-10",
        email: "o.brown@school.edu",
        phone: "0315-6789012",
        baseSalary: 52000,
        allowances: [
            { name: "House Rent", amount: 7800 },
            { name: "Transport", amount: 5000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4160 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 64800,
        netSalary: 60440,
    },
    {
        id: "sal-17",
        staffId: "staff-7",
        staffName: "Tariq Mehmood",
        department: "Transport",
        designation: "Driver",
        staffType: "non-teaching",
        joiningDate: "2019-08-20",
        email: "t.mehmood@school.edu",
        phone: "0316-7890123",
        baseSalary: 38000,
        allowances: [
            { name: "Transport", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 3040 },
        ],
        grossSalary: 41000,
        netSalary: 37960,
    },
    {
        id: "sal-18",
        staffId: "ins-11",
        staffName: "William Lee",
        department: "Computer Science",
        designation: "Head of Department",
        staffType: "teaching",
        joiningDate: "2017-06-01",
        email: "w.lee@school.edu",
        phone: "0317-8901234",
        bankAccount: "HBL-1122334455",
        baseSalary: 115000,
        allowances: [
            { name: "House Rent", amount: 17250 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
            { name: "HOD Allowance", amount: 10000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 9200 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 7500 },
        ],
        grossSalary: 150250,
        netSalary: 133350,
    },
    {
        id: "sal-19",
        staffId: "staff-8",
        staffName: "Nasreen Begum",
        department: "Kitchen",
        designation: "Cook",
        staffType: "non-teaching",
        joiningDate: "2020-02-15",
        email: "n.begum@school.edu",
        phone: "0318-9012345",
        baseSalary: 30000,
        allowances: [
            { name: "Transport", amount: 2500 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 2400 },
        ],
        grossSalary: 32500,
        netSalary: 30100,
    },
    {
        id: "sal-20",
        staffId: "ins-12",
        staffName: "Amir Raza",
        department: "Islamiat",
        designation: "Teacher",
        staffType: "teaching",
        joiningDate: "2021-09-01",
        email: "a.raza@school.edu",
        phone: "0319-0123456",
        baseSalary: 60000,
        allowances: [
            { name: "House Rent", amount: 9000 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4800 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 77000,
        netSalary: 72000,
    },
    {
        id: "sal-21",
        staffId: "staff-9",
        staffName: "Sadia Noor",
        department: "Administration",
        designation: "Receptionist",
        staffType: "admin",
        joiningDate: "2022-03-01",
        email: "s.noor@school.edu",
        phone: "0320-1234567",
        baseSalary: 42000,
        allowances: [
            { name: "House Rent", amount: 6300 },
            { name: "Transport", amount: 5000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 3360 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 53300,
        netSalary: 49740,
    },
    {
        id: "sal-22",
        staffId: "ins-13",
        staffName: "Daniel Kim",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
        department: "Science",
        designation: "Lab Instructor",
        staffType: "teaching",
        joiningDate: "2020-07-15",
        email: "d.kim@school.edu",
        phone: "0321-2345678",
        baseSalary: 58000,
        allowances: [
            { name: "House Rent", amount: 8700 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 4640 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 74700,
        netSalary: 69860,
    },
    {
        id: "sal-23",
        staffId: "staff-10",
        staffName: "Hassan Rauf",
        department: "Security",
        designation: "Head Security",
        staffType: "non-teaching",
        joiningDate: "2018-11-01",
        email: "h.rauf@school.edu",
        phone: "0322-3456789",
        bankAccount: "ABL-6677889900",
        baseSalary: 45000,
        allowances: [
            { name: "House Rent", amount: 6750 },
            { name: "Transport", amount: 4000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 3600 },
            { name: "Professional Tax", amount: 200 },
        ],
        grossSalary: 55750,
        netSalary: 51950,
    },
    {
        id: "sal-24",
        staffId: "ins-14",
        staffName: "Maria Garcia",
        avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=150",
        department: "English",
        designation: "Senior Teacher",
        staffType: "teaching",
        joiningDate: "2019-01-15",
        email: "m.garcia@school.edu",
        phone: "0323-4567890",
        bankAccount: "MCB-7788990011",
        baseSalary: 82000,
        allowances: [
            { name: "House Rent", amount: 12300 },
            { name: "Transport", amount: 5000 },
            { name: "Medical", amount: 3000 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 6560 },
            { name: "Professional Tax", amount: 200 },
            { name: "Income Tax", amount: 4100 },
        ],
        grossSalary: 102300,
        netSalary: 91440,
    },
    {
        id: "sal-25",
        staffId: "staff-11",
        staffName: "Bilal Ahmed",
        department: "Maintenance",
        designation: "Electrician",
        staffType: "non-teaching",
        joiningDate: "2020-04-01",
        email: "b.ahmed@school.edu",
        phone: "0324-5678901",
        baseSalary: 40000,
        allowances: [
            { name: "Transport", amount: 3500 },
        ],
        deductions: [
            { name: "Provident Fund", amount: 3200 },
        ],
        grossSalary: 43500,
        netSalary: 40300,
    },
];

// Payment History
export const salaryPayments: SalaryPayment[] = [
    {
        id: "pay-1",
        staffId: "ins-1",
        staffName: "Sarah Johnson",
        department: "Science",
        designation: "Senior Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 85000,
        totalAllowances: 20750,
        totalDeductions: 11250,
        grossSalary: 105750,
        netSalary: 94500,
        status: "paid",
        paidAmount: 94500,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-001",
    },
    {
        id: "pay-2",
        staffId: "ins-2",
        staffName: "Michael Chen",
        department: "Mathematics",
        designation: "Head of Department",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 120000,
        totalAllowances: 36000,
        totalDeductions: 17600,
        grossSalary: 156000,
        netSalary: 138400,
        status: "paid",
        paidAmount: 138400,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-002",
    },
    {
        id: "pay-3",
        staffId: "ins-3",
        staffName: "Emily Davis",
        department: "English",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 65000,
        totalAllowances: 17750,
        totalDeductions: 5400,
        grossSalary: 82750,
        netSalary: 77350,
        status: "paid",
        paidAmount: 77350,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-003",
    },
    {
        id: "pay-4",
        staffId: "staff-1",
        staffName: "Ahmed Khan",
        department: "Administration",
        designation: "Office Manager",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 55000,
        totalAllowances: 13250,
        totalDeductions: 4600,
        grossSalary: 68250,
        netSalary: 63650,
        status: "paid",
        paidAmount: 63650,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-004",
    },
    {
        id: "pay-5",
        staffId: "ins-1",
        staffName: "Sarah Johnson",
        department: "Science",
        designation: "Senior Teacher",
        month: "Feb 2026",
        year: 2026,
        baseSalary: 85000,
        totalAllowances: 20750,
        totalDeductions: 11250,
        grossSalary: 105750,
        netSalary: 94500,
        status: "pending",
        paidAmount: 0,
    },
    {
        id: "pay-6",
        staffId: "ins-2",
        staffName: "Michael Chen",
        department: "Mathematics",
        designation: "Head of Department",
        month: "Feb 2026",
        year: 2026,
        baseSalary: 120000,
        totalAllowances: 36000,
        totalDeductions: 17600,
        grossSalary: 156000,
        netSalary: 138400,
        status: "pending",
        paidAmount: 0,
    },
    {
        id: "pay-7",
        staffId: "ins-3",
        staffName: "Emily Davis",
        department: "English",
        designation: "Teacher",
        month: "Feb 2026",
        year: 2026,
        baseSalary: 65000,
        totalAllowances: 17750,
        totalDeductions: 5400,
        grossSalary: 82750,
        netSalary: 77350,
        status: "pending",
        paidAmount: 0,
    },
    {
        id: "pay-8",
        staffId: "staff-2",
        staffName: "Fatima Bibi",
        department: "Maintenance",
        designation: "Cleaning Staff",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 32000,
        totalAllowances: 3000,
        totalDeductions: 2560,
        grossSalary: 35000,
        netSalary: 32440,
        status: "paid",
        paidAmount: 32440,
        paidDate: "2026-01-28",
        paymentMode: "cash",
        transactionId: "TXN-20260128-005",
    },
    {
        id: "pay-9",
        staffId: "ins-4",
        staffName: "Robert Wilson",
        department: "History",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 70000,
        totalAllowances: 18500,
        totalDeductions: 9300,
        grossSalary: 88500,
        netSalary: 79200,
        status: "paid",
        paidAmount: 79200,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-006",
    },
    {
        id: "pay-10",
        staffId: "ins-5",
        staffName: "Jessica Taylor",
        department: "Science",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 68000,
        totalAllowances: 18200,
        totalDeductions: 9040,
        grossSalary: 86200,
        netSalary: 77160,
        status: "paid",
        paidAmount: 77160,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-007",
    },
    {
        id: "pay-11",
        staffId: "staff-3",
        staffName: "Muhammad Ali",
        department: "Security",
        designation: "Security Guard",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 35000,
        totalAllowances: 3000,
        totalDeductions: 2800,
        grossSalary: 38000,
        netSalary: 35200,
        status: "paid",
        paidAmount: 35200,
        paidDate: "2026-01-28",
        paymentMode: "cash",
        transactionId: "TXN-20260128-008",
    },
    {
        id: "pay-12",
        staffId: "ins-6",
        staffName: "David Miller",
        department: "Mathematics",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 62000,
        totalAllowances: 17300,
        totalDeductions: 5160,
        grossSalary: 79300,
        netSalary: 74140,
        status: "paid",
        paidAmount: 74140,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-009",
    },
    {
        id: "pay-13",
        staffId: "staff-4",
        staffName: "Zainab Hassan",
        department: "Library",
        designation: "Librarian",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 48000,
        totalAllowances: 12200,
        totalDeductions: 4040,
        grossSalary: 60200,
        netSalary: 56160,
        status: "paid",
        paidAmount: 56160,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-010",
    },
    {
        id: "pay-14",
        staffId: "ins-7",
        staffName: "Ayesha Malik",
        department: "Urdu",
        designation: "Senior Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 78000,
        totalAllowances: 19700,
        totalDeductions: 10340,
        grossSalary: 97700,
        netSalary: 87360,
        status: "paid",
        paidAmount: 87360,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-011",
    },
    {
        id: "pay-15",
        staffId: "ins-8",
        staffName: "James Anderson",
        department: "Physical Education",
        designation: "Sports Coach",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 55000,
        totalAllowances: 13250,
        totalDeductions: 4600,
        grossSalary: 68250,
        netSalary: 63650,
        status: "paid",
        paidAmount: 63650,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-012",
    },
    {
        id: "pay-16",
        staffId: "staff-5",
        staffName: "Rashid Hussain",
        department: "IT",
        designation: "System Administrator",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 72000,
        totalAllowances: 18800,
        totalDeductions: 9560,
        grossSalary: 90800,
        netSalary: 81240,
        status: "paid",
        paidAmount: 81240,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-013",
    },
    {
        id: "pay-17",
        staffId: "ins-9",
        staffName: "Sophia Martinez",
        department: "Art",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 58000,
        totalAllowances: 16700,
        totalDeductions: 4840,
        grossSalary: 74700,
        netSalary: 69860,
        status: "paid",
        paidAmount: 69860,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-014",
    },
    {
        id: "pay-18",
        staffId: "staff-6",
        staffName: "Imran Shah",
        department: "Accounts",
        designation: "Accountant",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 68000,
        totalAllowances: 18200,
        totalDeductions: 9040,
        grossSalary: 86200,
        netSalary: 77160,
        status: "paid",
        paidAmount: 77160,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-015",
    },
    {
        id: "pay-19",
        staffId: "ins-10",
        staffName: "Olivia Brown",
        department: "Music",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 52000,
        totalAllowances: 12800,
        totalDeductions: 4360,
        grossSalary: 64800,
        netSalary: 60440,
        status: "paid",
        paidAmount: 60440,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-016",
    },
    {
        id: "pay-20",
        staffId: "staff-7",
        staffName: "Tariq Mehmood",
        department: "Transport",
        designation: "Driver",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 38000,
        totalAllowances: 3000,
        totalDeductions: 3040,
        grossSalary: 41000,
        netSalary: 37960,
        status: "paid",
        paidAmount: 37960,
        paidDate: "2026-01-28",
        paymentMode: "cash",
        transactionId: "TXN-20260128-017",
    },
    {
        id: "pay-21",
        staffId: "ins-11",
        staffName: "William Lee",
        department: "Computer Science",
        designation: "Head of Department",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 115000,
        totalAllowances: 35250,
        totalDeductions: 16900,
        grossSalary: 150250,
        netSalary: 133350,
        status: "paid",
        paidAmount: 133350,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-018",
    },
    {
        id: "pay-22",
        staffId: "staff-8",
        staffName: "Nasreen Begum",
        department: "Kitchen",
        designation: "Cook",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 30000,
        totalAllowances: 2500,
        totalDeductions: 2400,
        grossSalary: 32500,
        netSalary: 30100,
        status: "paid",
        paidAmount: 30100,
        paidDate: "2026-01-28",
        paymentMode: "cash",
        transactionId: "TXN-20260128-019",
    },
    {
        id: "pay-23",
        staffId: "ins-12",
        staffName: "Amir Raza",
        department: "Islamiat",
        designation: "Teacher",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 60000,
        totalAllowances: 17000,
        totalDeductions: 5000,
        grossSalary: 77000,
        netSalary: 72000,
        status: "paid",
        paidAmount: 72000,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-020",
    },
    {
        id: "pay-24",
        staffId: "staff-9",
        staffName: "Sadia Noor",
        department: "Administration",
        designation: "Receptionist",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 42000,
        totalAllowances: 11300,
        totalDeductions: 3560,
        grossSalary: 53300,
        netSalary: 49740,
        status: "paid",
        paidAmount: 49740,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-021",
    },
    {
        id: "pay-25",
        staffId: "ins-13",
        staffName: "Daniel Kim",
        department: "Science",
        designation: "Lab Instructor",
        month: "Jan 2026",
        year: 2026,
        baseSalary: 58000,
        totalAllowances: 16700,
        totalDeductions: 4840,
        grossSalary: 74700,
        netSalary: 69860,
        status: "paid",
        paidAmount: 69860,
        paidDate: "2026-01-28",
        paymentMode: "bank_transfer",
        transactionId: "TXN-20260128-022",
    },
];

// Get unique departments
export const getDepartments = (): string[] => {
    const depts = [...new Set(staffSalaries.map(s => s.department))];
    return depts.sort();
};

// Get salary statistics
export const getSalaryStats = (): SalaryStats => {
    const totalBudget = staffSalaries.reduce((sum, s) => sum + s.netSalary, 0);
    const currentMonth = "Feb 2026";

    const currentMonthPayments = salaryPayments.filter(p => p.month === currentMonth);
    const paidPayments = currentMonthPayments.filter(p => p.status === "paid");
    const pendingPayments = currentMonthPayments.filter(p => p.status === "pending");

    return {
        totalBudget,
        paidThisMonth: paidPayments.reduce((sum, p) => sum + p.paidAmount, 0),
        pendingAmount: pendingPayments.reduce((sum, p) => sum + p.netSalary, 0),
        totalStaff: staffSalaries.length,
        paidStaff: paidPayments.length,
        pendingStaff: pendingPayments.length,
    };
};

// Get recent payments
export const getRecentPayments = (limit: number = 5): SalaryPayment[] => {
    return salaryPayments
        .filter(p => p.status === "paid")
        .sort((a, b) => new Date(b.paidDate!).getTime() - new Date(a.paidDate!).getTime())
        .slice(0, limit);
};
