import { TeachingStaff, NonTeachingStaff } from "@/lib/admin/types/staff";

export const teachingStaff: TeachingStaff[] = [
    {
        id: "t1",
        staffCode: "TCH-001",
        name: "Dr. Sarah Ahmed",
        email: "sarah.ahmed@school.edu",
        phone: "03001234567",
        whatsapp: "03001234567",
        cnic: "35201-1234567-1",
        gender: "Female",
        dateOfBirth: "1985-03-15",
        address: "House 45, Street 12, F-7/2, Islamabad",
        department: "Science",
        designation: "Senior Teacher",
        joiningDate: "2018-08-01",
        staffType: "teaching",
        status: "active",
        avatar: "/avatars/teacher1.jpg",
        salary: 85000,
        bankAccount: "PK36MEZN0099340012345678",
        subjects: ["Physics", "Mathematics"],
        classes: ["9", "10"],
        qualifications: ["PhD Physics", "M.Phil", "B.Ed"],
        specialization: "Quantum Mechanics",
    },
    {
        id: "t2",
        staffCode: "TCH-002",
        name: "Muhammad Usman Khan",
        email: "usman.khan@school.edu",
        phone: "03012345678",
        whatsapp: "03012345678",
        cnic: "35201-2345678-2",
        gender: "Male",
        dateOfBirth: "1990-07-22",
        address: "Apartment 12, Block C, Gulberg, Lahore",
        department: "Mathematics",
        designation: "Teacher",
        joiningDate: "2020-01-15",
        staffType: "teaching",
        status: "active",
        salary: 65000,
        bankAccount: "PK36MEZN0099340023456789",
        subjects: ["Mathematics", "Computer Science"],
        classes: ["7", "8", "9"],
        qualifications: ["MS Mathematics", "B.Sc"],
    },
    {
        id: "t3",
        staffCode: "TCH-003",
        name: "Fatima Zahra",
        email: "fatima.zahra@school.edu",
        phone: "03023456789",
        whatsapp: "03023456789",
        cnic: "35201-3456789-3",
        gender: "Female",
        dateOfBirth: "1988-11-10",
        address: "House 78, DHA Phase 5, Karachi",
        department: "English",
        designation: "Head of Department",
        joiningDate: "2015-06-01",
        staffType: "teaching",
        status: "active",
        avatar: "/avatars/teacher3.jpg",
        salary: 95000,
        bankAccount: "PK36MEZN0099340034567890",
        subjects: ["English Literature", "English Language"],
        classes: ["8", "9", "10"],
        qualifications: ["MA English", "TEFL Certified"],
        specialization: "Modern Literature",
    },
    {
        id: "t4",
        staffCode: "TCH-004",
        name: "Ahmed Raza",
        email: "ahmed.raza@school.edu",
        phone: "03034567890",
        cnic: "35201-4567890-4",
        gender: "Male",
        dateOfBirth: "1992-02-28",
        address: "House 23, Model Town, Lahore",
        department: "Science",
        designation: "Teacher",
        joiningDate: "2021-09-01",
        staffType: "teaching",
        status: "active",
        salary: 55000,
        subjects: ["Chemistry", "Biology"],
        classes: ["6", "7", "8"],
        qualifications: ["M.Sc Chemistry", "B.Ed"],
    },
    {
        id: "t5",
        staffCode: "TCH-005",
        name: "Ayesha Siddiqui",
        email: "ayesha.s@school.edu",
        phone: "03045678901",
        whatsapp: "03045678901",
        cnic: "35201-5678901-5",
        gender: "Female",
        dateOfBirth: "1995-09-18",
        address: "Flat 5, Galaxy Apartments, Rawalpindi",
        department: "Urdu",
        designation: "Teacher",
        joiningDate: "2022-03-15",
        staffType: "teaching",
        status: "on-leave",
        salary: 50000,
        subjects: ["Urdu", "Islamiat"],
        classes: ["5", "6", "7"],
        qualifications: ["MA Urdu", "B.Ed"],
    },
    {
        id: "t6",
        staffCode: "TCH-006",
        name: "Hassan Ali",
        email: "hassan.ali@school.edu",
        phone: "03056789012",
        cnic: "35201-6789012-6",
        gender: "Male",
        dateOfBirth: "1987-05-05",
        address: "House 90, Bahria Town, Islamabad",
        department: "Social Studies",
        designation: "Senior Teacher",
        joiningDate: "2016-04-01",
        staffType: "teaching",
        status: "active",
        avatar: "/avatars/teacher6.jpg",
        salary: 78000,
        bankAccount: "PK36MEZN0099340067890123",
        subjects: ["History", "Geography", "Civics"],
        classes: ["8", "9", "10"],
        qualifications: ["MA History", "M.Ed"],
        specialization: "South Asian History",
    },
    {
        id: "t7",
        staffCode: "TCH-007",
        name: "Zainab Malik",
        email: "zainab.m@school.edu",
        phone: "03067890123",
        cnic: "35201-7890123-7",
        gender: "Female",
        dateOfBirth: "1993-12-20",
        address: "House 34, G-11/4, Islamabad",
        department: "Computer Science",
        designation: "Teacher",
        joiningDate: "2019-08-15",
        staffType: "teaching",
        status: "active",
        salary: 70000,
        subjects: ["Computer Science", "IT"],
        classes: ["9", "10"],
        qualifications: ["MS Computer Science", "BS CS"],
        specialization: "Web Development",
    },
    {
        id: "t8",
        staffCode: "TCH-008",
        name: "Bilal Qureshi",
        email: "bilal.q@school.edu",
        phone: "03078901234",
        whatsapp: "03078901234",
        cnic: "35201-8901234-8",
        gender: "Male",
        dateOfBirth: "1991-08-12",
        address: "House 56, Wapda Town, Lahore",
        department: "Physical Education",
        designation: "Sports Coordinator",
        joiningDate: "2017-02-01",
        staffType: "teaching",
        status: "active",
        avatar: "/avatars/teacher8.jpg",
        salary: 60000,
        subjects: ["Physical Education"],
        classes: ["5", "6", "7", "8", "9", "10"],
        qualifications: ["BS Sports Sciences", "Coaching Certificate"],
        specialization: "Cricket & Football",
    },
];

export const nonTeachingStaff: NonTeachingStaff[] = [
    {
        id: "nt1",
        staffCode: "NTS-001",
        name: "Muhammad Irfan",
        email: "irfan@school.edu",
        phone: "03101234567",
        whatsapp: "03101234567",
        cnic: "35201-1111111-1",
        gender: "Male",
        dateOfBirth: "1980-04-10",
        address: "House 12, I-10/2, Islamabad",
        department: "Administration",
        designation: "Office Manager",
        joiningDate: "2010-01-15",
        staffType: "non-teaching",
        status: "active",
        avatar: "/avatars/staff1.jpg",
        salary: 75000,
        bankAccount: "PK36MEZN0099340011111111",
        role: "Administrative Head",
        shift: "full-day",
        workArea: "Main Office",
    },
    {
        id: "nt2",
        staffCode: "NTS-002",
        name: "Aisha Begum",
        email: "aisha.b@school.edu",
        phone: "03112345678",
        cnic: "35201-2222222-2",
        gender: "Female",
        dateOfBirth: "1985-09-25",
        address: "House 45, G-9/4, Islamabad",
        department: "Finance",
        designation: "Accountant",
        joiningDate: "2015-06-01",
        staffType: "non-teaching",
        status: "active",
        salary: 65000,
        bankAccount: "PK36MEZN0099340022222222",
        role: "Accounts Manager",
        shift: "full-day",
        workArea: "Finance Department",
    },
    {
        id: "nt3",
        staffCode: "NTS-003",
        name: "Rizwan Ahmed",
        email: "rizwan@school.edu",
        phone: "03123456789",
        cnic: "35201-3333333-3",
        gender: "Male",
        dateOfBirth: "1975-02-14",
        address: "House 78, F-8/3, Islamabad",
        department: "IT",
        designation: "IT Administrator",
        joiningDate: "2012-03-01",
        staffType: "non-teaching",
        status: "active",
        avatar: "/avatars/staff3.jpg",
        salary: 80000,
        bankAccount: "PK36MEZN0099340033333333",
        role: "System Administrator",
        shift: "full-day",
        workArea: "IT Lab",
    },
    {
        id: "nt4",
        staffCode: "NTS-004",
        name: "Nasreen Bibi",
        email: "nasreen@school.edu",
        phone: "03134567890",
        cnic: "35201-4444444-4",
        gender: "Female",
        dateOfBirth: "1982-07-30",
        address: "House 23, I-8/1, Islamabad",
        department: "Library",
        designation: "Librarian",
        joiningDate: "2014-08-15",
        staffType: "non-teaching",
        status: "active",
        salary: 55000,
        role: "Head Librarian",
        shift: "full-day",
        workArea: "Main Library",
    },
    {
        id: "nt5",
        staffCode: "NTS-005",
        name: "Kashif Mehmood",
        email: "kashif@school.edu",
        phone: "03145678901",
        whatsapp: "03145678901",
        cnic: "35201-5555555-5",
        gender: "Male",
        dateOfBirth: "1988-11-08",
        address: "House 56, G-10/4, Islamabad",
        department: "Security",
        designation: "Security Supervisor",
        joiningDate: "2018-01-01",
        staffType: "non-teaching",
        status: "active",
        salary: 45000,
        role: "Security Head",
        shift: "morning",
        workArea: "Campus Entrance",
    },
    {
        id: "nt6",
        staffCode: "NTS-006",
        name: "Rashida Parveen",
        email: "rashida@school.edu",
        phone: "03156789012",
        cnic: "35201-6666666-6",
        gender: "Female",
        dateOfBirth: "1990-03-22",
        address: "House 89, F-10/3, Islamabad",
        department: "Administration",
        designation: "Receptionist",
        joiningDate: "2020-05-01",
        staffType: "non-teaching",
        status: "active",
        salary: 40000,
        role: "Front Desk Officer",
        shift: "full-day",
        workArea: "Reception",
    },
    {
        id: "nt7",
        staffCode: "NTS-007",
        name: "Tariq Hussain",
        email: "tariq@school.edu",
        phone: "03167890123",
        cnic: "35201-7777777-7",
        gender: "Male",
        dateOfBirth: "1978-06-15",
        address: "House 12, G-7/2, Islamabad",
        department: "Maintenance",
        designation: "Maintenance Supervisor",
        joiningDate: "2011-09-01",
        staffType: "non-teaching",
        status: "active",
        avatar: "/avatars/staff7.jpg",
        salary: 50000,
        role: "Facility Manager",
        shift: "full-day",
        workArea: "Campus Wide",
    },
    {
        id: "nt8",
        staffCode: "NTS-008",
        name: "Saima Noor",
        email: "saima@school.edu",
        phone: "03178901234",
        cnic: "35201-8888888-8",
        gender: "Female",
        dateOfBirth: "1992-12-05",
        address: "House 34, F-6/1, Islamabad",
        department: "Health",
        designation: "School Nurse",
        joiningDate: "2019-04-15",
        staffType: "non-teaching",
        status: "on-leave",
        salary: 55000,
        role: "Medical Officer",
        shift: "full-day",
        workArea: "Medical Room",
        emergencyContact: "Noor Ahmed",
        emergencyPhone: "03189012345",
    },
];

// Helper functions
export function getUniqueDepartments(staffType: "teaching" | "non-teaching"): string[] {
    const staff = staffType === "teaching" ? teachingStaff : nonTeachingStaff;
    return [...new Set(staff.map((s) => s.department))].sort();
}

export function searchStaff<T extends { name: string; email: string; staffCode: string; department: string }>(
    staffList: T[],
    query: string
): T[] {
    if (!query.trim()) return staffList;
    const lowerQuery = query.toLowerCase();
    return staffList.filter(
        (s) =>
            s.name.toLowerCase().includes(lowerQuery) ||
            s.email.toLowerCase().includes(lowerQuery) ||
            s.staffCode.toLowerCase().includes(lowerQuery) ||
            s.department.toLowerCase().includes(lowerQuery)
    );
}
